"use client";

import * as React from "react";
import {
  LayoutDashboard,
  Youtube,
  KanbanSquare,
  Film,
  Sparkles,
  TrendingUp,
  CalendarDays,
  CheckSquare,
  Users,
  FolderOpen,
  Wallet,
  Target,
  BarChart3,
  Workflow,
  Settings,
  LayoutGrid,
  Search,
  Command,
  Moon,
  Sun,
  Plus,
  Bell,
  Menu,
  X,
  ChevronRight,
  ChevronDown,
  Pin,
  PinOff,
  Trash2,
  Edit3,
  Copy,
  Check,
  Clock,
  Flame,
  Bookmark,
  ExternalLink,
  Play,
  Pause,
  Circle,
  CircleDot,
  ArrowUpRight,
  ArrowDownRight,
  Download,
  Upload,
  Filter,
  MoreHorizontal,
  Star,
  AlertTriangle,
  CheckCircle2,
  Info,
  Lightbulb,
  Timer,
  Brain,
  Zap,
  Rocket,
  Trophy,
  Heart,
  Eye,
  ThumbsUp,
  MessageCircle,
  DollarSign,
  Users2,
  Activity,
  Gauge,
  ListChecks,
  FileText,
  Music,
  Image as ImageIcon,
  Palette,
  FileBox,
  TrendingDown,
  Globe,
  Languages,
  Shield,
  Database,
  RefreshCw,
  Keyboard,
  StickyNote,
  BookOpen,
  ClipboardList,
  Link2,
  type LucideProps,
} from "lucide-react";

const map: Record<string, React.ComponentType<LucideProps>> = {
  "layout-dashboard": LayoutDashboard,
  youtube: Youtube,
  "kanban-square": KanbanSquare,
  film: Film,
  sparkles: Sparkles,
  "trending-up": TrendingUp,
  "calendar-days": CalendarDays,
  "check-square": CheckSquare,
  users: Users,
  "folder-open": FolderOpen,
  wallet: Wallet,
  target: Target,
  "bar-chart-3": BarChart3,
  workflow: Workflow,
  settings: Settings,
  "layout-grid": LayoutGrid,
  search: Search,
  command: Command,
  moon: Moon,
  sun: Sun,
  plus: Plus,
  bell: Bell,
  menu: Menu,
  x: X,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  pin: Pin,
  "pin-off": PinOff,
  trash: Trash2,
  edit: Edit3,
  copy: Copy,
  check: Check,
  clock: Clock,
  flame: Flame,
  bookmark: Bookmark,
  "external-link": ExternalLink,
  play: Play,
  pause: Pause,
  circle: Circle,
  "circle-dot": CircleDot,
  "arrow-up-right": ArrowUpRight,
  "arrow-down-right": ArrowDownRight,
  download: Download,
  upload: Upload,
  filter: Filter,
  "more-horizontal": MoreHorizontal,
  star: Star,
  "alert-triangle": AlertTriangle,
  "check-circle": CheckCircle2,
  "check-circle-2": CheckCircle2,
  info: Info,
  lightbulb: Lightbulb,
  timer: Timer,
  brain: Brain,
  zap: Zap,
  rocket: Rocket,
  trophy: Trophy,
  heart: Heart,
  eye: Eye,
  thumbsup: ThumbsUp,
  message: MessageCircle,
  dollar: DollarSign,
  users2: Users2,
  activity: Activity,
  gauge: Gauge,
  "list-checks": ListChecks,
  "file-text": FileText,
  music: Music,
  image: ImageIcon,
  palette: Palette,
  "file-box": FileBox,
  "trending-down": TrendingDown,
  globe: Globe,
  languages: Languages,
  shield: Shield,
  database: Database,
  refresh: RefreshCw,
  keyboard: Keyboard,
  "sticky-note": StickyNote,
  "book-open": BookOpen,
  "clipboard-list": ClipboardList,
  link: Link2,
};

export interface IconProps extends LucideProps {
  name: string;
}

export function Icon({ name, ...props }: IconProps) {
  const Cmp = map[name] ?? Circle;
  return <Cmp {...props} />;
}
